### ISSUE TITLE
JS Bug

### ISSUE THREAD

**Issue by Lagicrus** [Portsmouth-Computing/py_chator#2]
![image](https://user-images.githubusercontent.com/24227350/43810668-e5506e76-9ab0-11e8-86c6-e01c88469f35.png)
On page load, this error occurs
If @WillGreen98 can fix this and then update the online.js so it refers to the right function that would be grand. The function it calls is supposed to restart the message GETing process in the event that a network error occurs then gets "fixed".
Let me know if you need the server running to test it against

**Comment by Mercer01** [comment]
didn't I remove this code?

**Comment by Mercer01** [comment]
@Lagicrus retest
